### ISSUE TITLE
Add bootstrap or any kind of CSS improvement to site

### ISSUE THREAD

**Issue by trowbrsa** [trowbrsa/DogWalker#4]
My current design has one background image for all pages as the over "CSS" design. It's hideous. If anyone has any interest in improving the look of the site, I would love your help!

**Comment by noglows** [comment]
Hey Sarah, can I help out with the Bootstrapping?

**Comment by trowbrsa** [comment]
Absolutely! It's reaaal ugly right now, thanks for your help!
