### ISSUE TITLE
Add navigation bar when users are logged in

### ISSUE THREAD

**Issue by trowbrsa** [trowbrsa/DogWalker#7]
Right now, it doesn't exist.

**Comment by loganmeetsworld** [comment]
I can help with this! Are you using any CSS framework currently?

**Comment by trowbrsa** [comment]
Thanks, Logan! No CSS framework currently, but @noglows offered to add general Bootstrap styling to the site.

**Comment by loganmeetsworld** [comment]
@trowbrsa I'll check it out and make it so it's compatible with bootstrap if added.

**Comment by loganmeetsworld** [comment]
Done!
